version: "3"
virtualmachines:
- name: host1
  image: rhel-cloud/rhel-8
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
  
- name: host2
  image: rhel-cloud/rhel-8
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2