version: "2"
containers:
- name: rhel
  image: redhat/ubi8
  shell: /bin/bash
  memory: 2048
#virtualmachines:
#- name: rhel
#  image: instruqt-redhat/rhel-latest
#  shell: /bin/bash
#  environment:
#    TERM: xterm
#  machine_type: n1-standard-2
