#!/bin/bash

# Create an output file
touch /root/post-run.log
# install nfs-utils package for showmount
yum install -y nfs-utils
# Create a done file to signal we have finished
touch /root/post-run.log.done