#!/bin/bash

# Create an output file
touch /root/post-run.log
# register host
dnf remove -y google-rhui-client-rhel8.noarch
rm -f /etc/yum.repos.d/google-cloud.repo
dnf clean all
subscription-manager config --rhsm.manage_repos=1
subscription-manager register --force --name=rhel --org=12451665 --activationkey=Instruqt_system_registration
# Download the configuration
dnf install -y wget
wget https://raw.githubusercontent.com/rhel-labs/learn-katacoda/master/instruqt/imagebuilder-cli/assets/node-app-server.toml
# Create a done file to signal we have finished
touch /root/post-run.log.done
