#!/bin/bash

# Create an output file
touch /root/post-run.log
# Download the configuration
wget https://github.com/rhel-labs/learn-katacoda/blame/master/instruqt/imagebuilder-cli/assets/node-app-server.toml
# Create a done file to signal we have finished
touch /root/post-run.log.done
