#!/bin/bash

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "adding cockpit" >> /root/post-run.log
yum -y install cockpit cockpit-packagekit

echo "starting cockpit" >> /root/post-run.log
systemctl start cockpit

#Set the password expiry for the rhel user to never
chage -M -1 rhel

echo "DONE" >> /root/post-run.log
sudo chmod +x ./install_sql.sh
sudo ./install_sql.sh
export HOSTNAME=`hostname --all-fqdns`
