#!/bin/bash

dnf install -y man-db

# creating sample directory
/usr/bin/touch {anaconda-ks.cfg,original-ks.cfg}
/usr/bin/mkdir /root/openscap_data
/usr/bin/touch /root/openscap_data/{eval_remediate_report.html,eval_remediate_results.xml}
