version: "2"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-5-tmm-22-01-v1
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
